### ISSUE TITLE
Add SNB PRM subplement

### ISSUE THREAD

**Issue by uis246** [Igalia/intel-osrc-gfx-prm#1]
`Supplement to Volume 3 Part 3: PCH Display Registers`

**Comment by jasuarez** [comment]
Already there (https://github.com/Igalia/intel-osrc-gfx-prm/blob/master/003_snb_-_2011/snb_ihd_os_vol3_part3.pdf)

**Comment by uis246** [comment]
snb_ihd_os_vol3_part3b_register_offsets.pdf

**Comment by uis246** [comment]
https://01.org/sites/default/files/documentation/snb_ihd_os_vol3_part3b_register_offsets.pdf

**Comment by jasuarez** [comment]
Ah, thanks. Added.
