### ISSUE TITLE
Dg2 manuals?

### ISSUE THREAD

**Issue by oscarbg** [Igalia/intel-osrc-gfx-prm#2]

**Comment by uis246** [comment]
You mean Alchemist?

**Comment by jamezchard** [comment]
> You mean Alchemist?

You can find it here https://www.intel.com/content/www/us/en/docs/graphics-for-linux/developer-reference/1-0/alchemist-arctic-sound-m.html

**Comment by jaxiah** [comment]
You can find it here https://www.intel.com/content/www/us/en/docs/graphics-for-linux/developer-reference/1-0/alchemist-arctic-sound-m.html

**Comment by uis246** [comment]
https://github.com/uis246/intel-osrc-gfx-prm/tree/master/021_acm_-_2023
It was in my tree for a long time

**Comment by oscarbg** [comment]
Thanks @uis246!! Going to close but any news on xe2 docs on lunar lake..

**Comment by uis246** [comment]
Considering ACM docs were released one year after GPU, I expect xe2 docs being released somewhere in September 2025.
They will probably appear on [x.org](https://www.x.org/docs/intel/?C=M;O=D).
